# Generated by Django 3.0.3 on 2020-02-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tof', '0003_auto_20191127_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatablefield',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
